export const HeroImages = [
  "/Hero/hero1.avif",
  "/Hero/hero2.jpg",
  "/Hero/hero3.webp",
  "/Hero/hero4.webp",
];

export const MenuItems = [
  { title: "Home", href: "/" },
  { title: "Productos", href: "/product-list" },
  { title: "Acerca de", href: "/about" },
  { title: "Contacto", href: "/contact" },
];
export const iphoneProducts = [
  {
    _type: "product",
    name: "iPhone 14 Pro Max",
    slug: { _type: "slug", current: "iphone-14-pro-max-nuevo" },
    model: "iPhone 14 Pro Max",
    storage: "256GB",
    color: "Negro espacial",
    batteryHealth: 100,
    includesBox: true,
    includesCharger: true,
    price: 999000,
    description: "Nuevo, sellado. Garantía oficial Apple.",
    featured: true,
    image: { asset: { _type: "reference", _ref: "imgIphone14" } },
    category: { _type: "reference", _ref: "catIphone" },
    condition: { _type: "reference", _ref: "condNuevo" },
  },
  {
    _type: "product",
    name: "iPhone 13 Usado",
    slug: { _type: "slug", current: "iphone-13-usado" },
    model: "iPhone 13",
    storage: "128GB",
    color: "Azul medianoche",
    batteryHealth: 88,
    includesBox: false,
    includesCharger: false,
    price: 685000,
    description: "Usado en buen estado. Sin caja ni cargador.",
    featured: false,
    image: { asset: { _type: "reference", _ref: "imgIphone13" } },
    category: { _type: "reference", _ref: "catIphone" },
    condition: { _type: "reference", _ref: "condUsado" },
  },
  {
    _type: "product",
    name: "iPhone 12 Reacondicionado",
    slug: { _type: "slug", current: "iphone-12-reacondicionado" },
    model: "iPhone 12",
    storage: "64GB",
    color: "Blanco",
    batteryHealth: 93,
    includesBox: true,
    includesCharger: true,
    price: 525000,
    description: "Revisado y restaurado por técnicos certificados.",
    featured: true,
    image: { asset: { _type: "reference", _ref: "imgIphone12" } },
    category: { _type: "reference", _ref: "catIphone" },
    condition: { _type: "reference", _ref: "condReacondicionado" },
  },
];
